### ISSUE TITLE
clojure.spec.alpha/form should return ::undefined for anonym functions

### ISSUE THREAD

**Issue by mathesz** [babashka/spec.alpha#1]
The `clojure.spec.alpha/form` function calls `fn-sym` which returns a wrong value for anonym functions:

```
(defn- fn-sym [^Object f]
  (let [[_ f-ns f-n] (re-matches #"(.*)\$(.*?)(__[0-9]+)?" (.. f getClass getName))]
    ;; check for anonymous function
    (when (not= "fn" f-n)
      (symbol (demunge f-ns) (demunge f-n)))))
```
https://github.com/babashka/spec.alpha/blob/babashka/src/main/clojure/clojure/spec/alpha.clj#L146-L150
**Expected behavior:**

The function should return `nil` for anonym functions.

**Current behavior:**

Symbolic value of the function is returned, such as `sci.impl.fns/fun/arity-0`

The regular expression and the `when` condition fails to ignore sci anonym functions.

```
(re-matches #"(.*)\$(.*?)(__[-1-9]+)?" "sci.impl.fns$fun$arity_-1__7418@31425281")
=> ["sci.impl.fns$fun$arity_-1__7418@31425281" "sci.impl.fns$fun" "arity_-1__7418@31425281" nil]
```
The string `"arity_-1__7418@31425281"` becomes `f-n` which is `not= "fn"` , therefore the when condition returns a demunged symbol for the anonym function insted of the correct `nil` value.

**Impact**

`(clojure.spec.alpha/form (fn [] true))` => `sci.impl.fns/fun/arity-0`

This should be `:clojure.spec.alpha/undefined` as per
https://github.com/babashka/spec.alpha/blob/babashka/src/main/clojure/clojure/spec/alpha.clj#L169

**Comment by borkdude** [comment]
Thanks.
